// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: internal/testdata/num.proto

package testdata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Num struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	N             int64                  `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	S             string                 `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Num) Reset() {
	*x = Num{}
	mi := &file_internal_testdata_num_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Num) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Num) ProtoMessage() {}

func (x *Num) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testdata_num_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Num.ProtoReflect.Descriptor instead.
func (*Num) Descriptor() ([]byte, []int) {
	return file_internal_testdata_num_proto_rawDescGZIP(), []int{0}
}

func (x *Num) GetN() int64 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *Num) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

var File_internal_testdata_num_proto protoreflect.FileDescriptor

var file_internal_testdata_num_proto_rawDesc = string([]byte{
	0x0a, 0x1b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x64,
	0x61, 0x74, 0x61, 0x2f, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x74,
	0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x22, 0x21, 0x0a, 0x03, 0x4e, 0x75, 0x6d, 0x12, 0x0c,
	0x0a, 0x01, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x6e, 0x12, 0x0c, 0x0a, 0x01,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x73, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x72, 0x67, 0x6f, 0x73, 0x2d, 0x69,
	0x6f, 0x2f, 0x61, 0x72, 0x67, 0x6f, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var (
	file_internal_testdata_num_proto_rawDescOnce sync.Once
	file_internal_testdata_num_proto_rawDescData []byte
)

func file_internal_testdata_num_proto_rawDescGZIP() []byte {
	file_internal_testdata_num_proto_rawDescOnce.Do(func() {
		file_internal_testdata_num_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_testdata_num_proto_rawDesc), len(file_internal_testdata_num_proto_rawDesc)))
	})
	return file_internal_testdata_num_proto_rawDescData
}

var file_internal_testdata_num_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_testdata_num_proto_goTypes = []any{
	(*Num)(nil), // 0: testdata.Num
}
var file_internal_testdata_num_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_testdata_num_proto_init() }
func file_internal_testdata_num_proto_init() {
	if File_internal_testdata_num_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_testdata_num_proto_rawDesc), len(file_internal_testdata_num_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_testdata_num_proto_goTypes,
		DependencyIndexes: file_internal_testdata_num_proto_depIdxs,
		MessageInfos:      file_internal_testdata_num_proto_msgTypes,
	}.Build()
	File_internal_testdata_num_proto = out.File
	file_internal_testdata_num_proto_goTypes = nil
	file_internal_testdata_num_proto_depIdxs = nil
}
