// Package ir is the intermediate representation for argos stub generation.
package ir

import (
	"fmt"
	"strings"
	"unicode"

	"github.com/argos-io/argos/descriptor"
)

// Shape is the RPC call pattern. Values match descriptor.Shape.
type Shape = descriptor.Shape

const (
	Unary           = descriptor.Unary
	ServerStreaming = descriptor.ServerStreaming
	ClientStreaming = descriptor.ClientStreaming
	BidiStreaming   = descriptor.BidiStreaming
)

const (
	Version1 = 1
	Version2 = 2
)

const (
	SourceProto  = "proto"
	SourcePlugin = "plugin"
	SourceIR     = "ir"
)

// File describes generated Go units (*.pb.go / *.msg.go + *.argos.go).
type File struct {
	IRVersion    int       `json:"ir_version,omitempty"`
	Source       string    `json:"source,omitempty"`
	GoPackage    string    `json:"go_package"`
	GoModule     string    `json:"go_module,omitempty"`
	ProtoPackage string    `json:"proto_package,omitempty"`
	InputBase    string    `json:"input_base,omitempty"`
	Outputs      Outputs   `json:"outputs,omitempty"`
	OutputName   string    `json:"output_name,omitempty"` // legacy stub output name
	Messages     []Message `json:"messages,omitempty"`
	Services     []Service `json:"services"`
	// FileDescriptor is a serialized google.protobuf.FileDescriptorProto (proto frontend).
	FileDescriptor []byte `json:"file_descriptor,omitempty"`
	// FileDescriptorSet contains the input file and its linked dependencies.
	// It lets message generation validate linked descriptors without requiring
	// those descriptors to be registered globally. Imported Go types still need
	// to be generated by their own file/package.
	FileDescriptorSet []byte `json:"file_descriptor_set,omitempty"`
}

// Outputs names message and stub artifacts.
type Outputs struct {
	Messages string `json:"messages,omitempty"`
	Stub     string `json:"stub,omitempty"`
}

// Message is one generated message type.
type Message struct {
	GoName string  `json:"go_name"`
	Fields []Field `json:"fields,omitempty"`
}

// Field is one field on a message.
type Field struct {
	GoName      string `json:"go_name"`
	Number      int32  `json:"number"`
	Kind        string `json:"kind"`
	MessageType string `json:"message_type,omitempty"`
	EnumType    string `json:"enum_type,omitempty"`
}

// Service is one protobuf-style service definition.
type Service struct {
	GoName   string   `json:"go_name"`
	FullName string   `json:"full_name,omitempty"` // protobuf dotted name, e.g. echo.v1.EchoService
	Methods  []Method `json:"methods"`
}

// Method is one RPC on a service.
type Method struct {
	GoName       string `json:"go_name"`
	FullName     string `json:"full_name"` // protobuf dotted name, e.g. echo.v1.EchoService.Echo
	InputType    string `json:"input_type"`
	OutputType   string `json:"output_type"`
	Shape        Shape  `json:"shape,omitempty"`
	ServerStream bool   `json:"server_stream,omitempty"` // derived from Shape; kept for stubgen
	ClientStream bool   `json:"client_stream,omitempty"` // derived from Shape; kept for stubgen
}

// ShapeFromStreams maps client/server streaming flags to Shape.
func ShapeFromStreams(clientStream, serverStream bool) Shape {
	switch {
	case clientStream && serverStream:
		return BidiStreaming
	case serverStream:
		return ServerStreaming
	case clientStream:
		return ClientStreaming
	default:
		return Unary
	}
}

// StreamsFromShape maps Shape to client/server streaming flags.
func StreamsFromShape(shape Shape) (clientStream, serverStream bool) {
	switch shape {
	case ServerStreaming:
		return false, true
	case ClientStreaming:
		return true, false
	case BidiStreaming:
		return true, true
	default:
		return false, false
	}
}

// NormalizeShape makes Shape and ServerStream/ClientStream consistent.
// Shape is authoritative when non-zero; otherwise flags derive Shape.
func (m *Method) NormalizeShape() {
	if m.Shape != 0 {
		m.ClientStream, m.ServerStream = StreamsFromShape(m.Shape)
		return
	}
	m.Shape = ShapeFromStreams(m.ClientStream, m.ServerStream)
}

// Version returns the IR version (1 when unset and no messages).
func (f *File) Version() int {
	if f.IRVersion != 0 {
		return f.IRVersion
	}
	if len(f.Messages) > 0 || len(f.FileDescriptor) > 0 || len(f.FileDescriptorSet) > 0 {
		return Version2
	}
	return Version1
}

// StubName returns the stub output filename.
func (f *File) StubName() string {
	if f.Outputs.Stub != "" {
		return f.Outputs.Stub
	}
	if f.OutputName != "" {
		return f.OutputName
	}
	if f.InputBase != "" {
		return f.InputBase + ".argos.go"
	}
	return ""
}

// MessagesName returns the message output filename.
func (f *File) MessagesName() string {
	if f.Outputs.Messages != "" {
		return f.Outputs.Messages
	}
	if f.InputBase == "" {
		return ""
	}
	switch f.Source {
	case SourceProto:
		return f.InputBase + ".pb.go"
	default:
		return f.InputBase + ".msg.go"
	}
}

// GenerateMessages reports whether message output should be produced.
func (f *File) GenerateMessages() bool {
	return f.MessagesName() != "" && (len(f.Messages) > 0 || len(f.FileDescriptor) > 0 || len(f.FileDescriptorSet) > 0)
}

// Validate checks IR consistency for generation.
func (f *File) Validate(fromPlugin bool) error {
	if f.GoPackage == "" {
		return fmt.Errorf("ir: missing go_package")
	}
	if _, err := PackageName(f.GoPackage); err != nil {
		return err
	}
	if len(f.Services) == 0 {
		return fmt.Errorf("ir: no services")
	}
	if f.StubName() == "" {
		return fmt.Errorf("ir: missing stub output name")
	}
	if err := ValidateNames(f); err != nil {
		return err
	}
	if fromPlugin && f.Version() >= Version2 && len(f.Messages) == 0 && len(f.FileDescriptor) == 0 && len(f.FileDescriptorSet) == 0 {
		return fmt.Errorf("ir: plugin IR v2 must include messages, file_descriptor, or file_descriptor_set")
	}
	if f.GenerateMessages() {
		if err := validateMessageRefs(f); err != nil {
			return err
		}
	}
	return nil
}

// ValidateNames checks the identifiers that code generators interpolate into
// Go source. It is also used by generators directly, so malformed plugin IR
// fails before it can produce uncompilable output.
func ValidateNames(f *File) error {
	seenMessages := make(map[string]struct{}, len(f.Messages))
	for _, msg := range f.Messages {
		if err := requireIdentifier("message", msg.GoName); err != nil {
			return err
		}
		if _, exists := seenMessages[msg.GoName]; exists {
			return fmt.Errorf("ir: duplicate message name %q", msg.GoName)
		}
		seenMessages[msg.GoName] = struct{}{}
		seenFields := make(map[string]struct{}, len(msg.Fields))
		seenNumbers := make(map[int32]struct{}, len(msg.Fields))
		for _, field := range msg.Fields {
			if err := requireIdentifier("field", field.GoName); err != nil {
				return err
			}
			if field.Number <= 0 {
				return fmt.Errorf("ir: field %q has invalid number %d", field.GoName, field.Number)
			}
			if _, exists := seenFields[field.GoName]; exists {
				return fmt.Errorf("ir: message %q has duplicate field %q", msg.GoName, field.GoName)
			}
			if _, exists := seenNumbers[field.Number]; exists {
				return fmt.Errorf("ir: message %q has duplicate field number %d", msg.GoName, field.Number)
			}
			seenFields[field.GoName] = struct{}{}
			seenNumbers[field.Number] = struct{}{}
		}
	}

	seenServices := make(map[string]struct{}, len(f.Services))
	seenPrefixes := make(map[string]string, len(f.Services))
	for _, service := range f.Services {
		if err := requireIdentifier("service", service.GoName); err != nil {
			return err
		}
		if _, exists := seenServices[service.GoName]; exists {
			return fmt.Errorf("ir: duplicate service name %q", service.GoName)
		}
		seenServices[service.GoName] = struct{}{}
		prefix := lowerFirst(strings.TrimSuffix(service.GoName, "Service"))
		if previous, exists := seenPrefixes[prefix]; exists {
			return fmt.Errorf("ir: services %q and %q generate the same Go prefix %q", previous, service.GoName, prefix)
		}
		seenPrefixes[prefix] = service.GoName

		if service.FullName != "" {
			if err := requireProtobufFullName("service", service.FullName); err != nil {
				return err
			}
		}
		seenMethods := make(map[string]struct{}, len(service.Methods))
		for _, method := range service.Methods {
			if err := requireIdentifier("method", method.GoName); err != nil {
				return err
			}
			if err := requireIdentifier("input type", method.InputType); err != nil {
				return err
			}
			if err := requireIdentifier("output type", method.OutputType); err != nil {
				return err
			}
			if method.FullName != "" {
				if err := requireProtobufFullName("method", method.FullName); err != nil {
					return err
				}
			}
			if method.Shape > BidiStreaming {
				return fmt.Errorf("ir: method %q has invalid shape %d", method.GoName, method.Shape)
			}
			if _, exists := seenMethods[method.GoName]; exists {
				return fmt.Errorf("ir: service %q has duplicate method %q", service.GoName, method.GoName)
			}
			seenMethods[method.GoName] = struct{}{}
		}
	}
	return validateGeneratedSymbols(f)
}

// validateGeneratedSymbols protects the package-level names emitted by the
// stub generator. Distinct IDL names can otherwise concatenate into the same
// Go identifier and produce either uncompilable output or a dispatcher that
// routes two methods through one constant.
func validateGeneratedSymbols(f *File) error {
	seen := make(map[string]string)
	declare := func(name, kind string) error {
		if previous, exists := seen[name]; exists {
			return fmt.Errorf("ir: generated %s %q conflicts with %s", kind, name, previous)
		}
		seen[name] = kind
		return nil
	}

	for _, message := range f.Messages {
		if err := declare(message.GoName, "message type"); err != nil {
			return err
		}
	}
	for _, service := range f.Services {
		prefix := lowerFirst(strings.TrimSuffix(service.GoName, "Service"))
		for _, symbol := range []struct {
			name string
			kind string
		}{
			{service.GoName, "server interface"},
			{"Register" + service.GoName, "register function"},
			{service.GoName + "Client", "client interface"},
			{"New" + service.GoName + "Client", "client constructor"},
			{prefix + "Client", "client implementation"},
		} {
			if err := declare(symbol.name, symbol.kind); err != nil {
				return err
			}
		}
		for _, method := range service.Methods {
			if err := declare(prefix+method.GoName, "method constant"); err != nil {
				return err
			}
			if !method.ClientStream && !method.ServerStream {
				continue
			}
			for _, symbol := range []struct {
				name string
				kind string
			}{
				{service.GoName + "_" + method.GoName + "Server", "stream server interface"},
				{lowerFirst(service.GoName) + method.GoName + "Server", "stream server implementation"},
				{service.GoName + "_" + method.GoName + "Client", "stream client interface"},
				{lowerFirst(service.GoName) + method.GoName + "Client", "stream client implementation"},
			} {
				if err := declare(symbol.name, symbol.kind); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

func requireIdentifier(kind, name string) error {
	if !IsGoIdentifier(name) {
		return fmt.Errorf("ir: invalid Go %s identifier %q", kind, name)
	}
	return nil
}

// requireProtobufFullName rejects gRPC path form (/svc/method) and empty segments.
func requireProtobufFullName(kind, fullName string) error {
	if fullName == "" {
		return fmt.Errorf("ir: empty %s full name", kind)
	}
	if strings.Contains(fullName, "/") {
		return fmt.Errorf("ir: %s full name %q must be protobuf dotted form, not gRPC path", kind, fullName)
	}
	parts := strings.Split(fullName, ".")
	if len(parts) < 1 {
		return fmt.Errorf("ir: invalid %s full name %q", kind, fullName)
	}
	for _, seg := range parts {
		if seg == "" {
			return fmt.Errorf("ir: %s full name %q has empty segment", kind, fullName)
		}
	}
	return nil
}

// IsGoIdentifier reports whether name is a non-keyword Go identifier.
func IsGoIdentifier(name string) bool {
	if name == "" {
		return false
	}
	first := true
	for _, r := range name {
		if first {
			if r != '_' && !unicode.IsLetter(r) {
				return false
			}
			first = false
			continue
		}
		if r != '_' && !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			return false
		}
	}
	return !isGoKeyword(name) && name != "_"
}

func isGoKeyword(name string) bool {
	switch name {
	case "break", "default", "func", "interface", "select", "case", "defer", "go", "map", "struct",
		"chan", "else", "goto", "package", "switch", "const", "fallthrough", "if", "range", "type",
		"continue", "for", "import", "return", "var":
		return true
	default:
		return false
	}
}

func lowerFirst(name string) string {
	runes := []rune(name)
	if len(runes) != 0 {
		runes[0] = unicode.ToLower(runes[0])
	}
	return string(runes)
}

// PackageName returns the Go package identifier represented by go_package.
// Proto options commonly use "import/path;package", while older IR files in
// the wild use only an import path. Accept both forms and never emit an import
// path after the package keyword.
func PackageName(raw string) (string, error) {
	raw = strings.TrimSpace(raw)
	if i := strings.IndexByte(raw, ';'); i >= 0 {
		raw = strings.TrimSpace(raw[i+1:])
	}
	raw = strings.TrimRight(raw, "/\\")
	if i := strings.LastIndexAny(raw, "/\\"); i >= 0 {
		raw = raw[i+1:]
	}
	if raw == "" {
		return "", fmt.Errorf("ir: go_package has no package identifier")
	}
	for i, r := range raw {
		if (i == 0 && !(r == '_' || unicode.IsLetter(r))) ||
			(i > 0 && !(r == '_' || unicode.IsLetter(r) || unicode.IsDigit(r))) {
			return "", fmt.Errorf("ir: invalid go package identifier %q", raw)
		}
	}
	if isGoKeyword(raw) {
		return "", fmt.Errorf("ir: go package identifier %q is a keyword", raw)
	}
	return raw, nil
}

func validateMessageRefs(f *File) error {
	known := map[string]struct{}{}
	for _, msg := range f.Messages {
		known[msg.GoName] = struct{}{}
	}
	for _, svc := range f.Services {
		for _, method := range svc.Methods {
			if _, ok := known[method.InputType]; !ok && len(f.FileDescriptor) == 0 && len(f.FileDescriptorSet) == 0 {
				return fmt.Errorf("ir: unknown input type %q", method.InputType)
			}
			if !method.ServerStream {
				if _, ok := known[method.OutputType]; !ok && len(f.FileDescriptor) == 0 && len(f.FileDescriptorSet) == 0 {
					return fmt.Errorf("ir: unknown output type %q", method.OutputType)
				}
			} else if _, ok := known[method.OutputType]; !ok && len(f.FileDescriptor) == 0 && len(f.FileDescriptorSet) == 0 {
				return fmt.Errorf("ir: unknown stream output type %q", method.OutputType)
			}
		}
	}
	return nil
}

// Normalize fills default output names, version metadata, FullName, and Shape.
func (f *File) Normalize(fromPlugin bool) {
	if f.Source == "" {
		if fromPlugin {
			f.Source = SourcePlugin
		} else if len(f.FileDescriptor) > 0 || len(f.FileDescriptorSet) > 0 {
			f.Source = SourceProto
		} else {
			f.Source = SourceIR
		}
	}
	if f.Outputs.Stub == "" && f.OutputName != "" {
		f.Outputs.Stub = f.OutputName
	}
	if f.Outputs.Stub == "" && f.InputBase != "" {
		f.Outputs.Stub = f.InputBase + ".argos.go"
	}
	if f.OutputName == "" {
		f.OutputName = f.StubName()
	}
	if f.GenerateMessages() && f.Outputs.Messages == "" && f.InputBase != "" {
		if f.Source == SourceProto {
			f.Outputs.Messages = f.InputBase + ".pb.go"
		} else {
			f.Outputs.Messages = f.InputBase + ".msg.go"
		}
	}
	if f.Version() >= Version2 && f.IRVersion == 0 {
		f.IRVersion = Version2
	}
	for i := range f.Services {
		svc := &f.Services[i]
		if svc.FullName == "" {
			svc.FullName = serviceFullName(f.ProtoPackage, svc.GoName)
		} else if strings.Contains(svc.FullName, "/") {
			svc.FullName = strings.ReplaceAll(svc.FullName, "/", ".")
		}
		for j := range svc.Methods {
			method := &svc.Methods[j]
			method.NormalizeShape()
			if method.FullName == "" {
				method.FullName = svc.FullName + "." + method.GoName
			} else if strings.Contains(method.FullName, "/") {
				method.FullName = strings.ReplaceAll(method.FullName, "/", ".")
			}
		}
	}
}

func serviceFullName(protoPackage, goName string) string {
	if protoPackage == "" {
		return goName
	}
	return protoPackage + "." + goName
}
