// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: echo.proto

package testpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoMessage) Reset() {
	*x = EchoMessage{}
	mi := &file_echo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoMessage) ProtoMessage() {}

func (x *EchoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_echo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoMessage.ProtoReflect.Descriptor instead.
func (*EchoMessage) Descriptor() ([]byte, []int) {
	return file_echo_proto_rawDescGZIP(), []int{0}
}

func (x *EchoMessage) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_echo_proto protoreflect.FileDescriptor

const file_echo_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"echo.proto\x12\aecho.v1\"#\n" +
	"\vEchoMessage\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value2\xef\x01\n" +
	"\x04Echo\x123\n" +
	"\x05Unary\x12\x14.echo.v1.EchoMessage\x1a\x14.echo.v1.EchoMessage\x12<\n" +
	"\fClientStream\x12\x14.echo.v1.EchoMessage\x1a\x14.echo.v1.EchoMessage(\x01\x12<\n" +
	"\fServerStream\x12\x14.echo.v1.EchoMessage\x1a\x14.echo.v1.EchoMessage0\x01\x126\n" +
	"\x04Bidi\x12\x14.echo.v1.EchoMessage\x1a\x14.echo.v1.EchoMessage(\x010\x01B8Z6github.com/argos-io/argos/binding/grpc/internal/testpbb\x06proto3"

var (
	file_echo_proto_rawDescOnce sync.Once
	file_echo_proto_rawDescData []byte
)

func file_echo_proto_rawDescGZIP() []byte {
	file_echo_proto_rawDescOnce.Do(func() {
		file_echo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_echo_proto_rawDesc), len(file_echo_proto_rawDesc)))
	})
	return file_echo_proto_rawDescData
}

var file_echo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_echo_proto_goTypes = []any{
	(*EchoMessage)(nil), // 0: echo.v1.EchoMessage
}
var file_echo_proto_depIdxs = []int32{
	0, // 0: echo.v1.Echo.Unary:input_type -> echo.v1.EchoMessage
	0, // 1: echo.v1.Echo.ClientStream:input_type -> echo.v1.EchoMessage
	0, // 2: echo.v1.Echo.ServerStream:input_type -> echo.v1.EchoMessage
	0, // 3: echo.v1.Echo.Bidi:input_type -> echo.v1.EchoMessage
	0, // 4: echo.v1.Echo.Unary:output_type -> echo.v1.EchoMessage
	0, // 5: echo.v1.Echo.ClientStream:output_type -> echo.v1.EchoMessage
	0, // 6: echo.v1.Echo.ServerStream:output_type -> echo.v1.EchoMessage
	0, // 7: echo.v1.Echo.Bidi:output_type -> echo.v1.EchoMessage
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_echo_proto_init() }
func file_echo_proto_init() {
	if File_echo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_echo_proto_rawDesc), len(file_echo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_echo_proto_goTypes,
		DependencyIndexes: file_echo_proto_depIdxs,
		MessageInfos:      file_echo_proto_msgTypes,
	}.Build()
	File_echo_proto = out.File
	file_echo_proto_goTypes = nil
	file_echo_proto_depIdxs = nil
}
