// Package check holds helpers for comparing generated Go source.
package check

import "bytes"

// Normalize strips volatile header lines and normalizes newlines for diff.
func Normalize(b []byte) []byte {
	lines := bytes.Split(bytes.TrimSpace(bytes.ReplaceAll(b, []byte("\r\n"), []byte("\n"))), []byte("\n"))
	var out [][]byte
	for _, line := range lines {
		trimmed := bytes.TrimSpace(line)
		if bytes.HasPrefix(trimmed, []byte("// Code generated by")) {
			continue
		}
		if bytes.HasPrefix(trimmed, []byte("// source:")) {
			continue
		}
		if bytes.HasPrefix(trimmed, []byte("// versions:")) {
			continue
		}
		if bytes.HasPrefix(trimmed, []byte("// \tprotoc")) {
			continue
		}
		out = append(out, line)
	}
	return bytes.Join(out, []byte("\n"))
}
